# Generated by Django 2.1.3 on 2018-11-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencysChief',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRegister',
            fields=[
                ('Id_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DefencyMinistry',
            fields=[
                ('Id_no', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('contact_no', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
            ],
        ),
    ]
