# Generated by Django 2.1.3 on 2018-12-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appprotector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefencyMinistryRegister',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('contact_no', models.IntegerField()),
                ('Email_id', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DefencyMinistry',
        ),
        migrations.RemoveField(
            model_name='agentregister',
            name='City',
        ),
        migrations.RemoveField(
            model_name='agentregister',
            name='Id_no',
        ),
        migrations.RemoveField(
            model_name='agentregister',
            name='State',
        ),
    ]
