# Generated by Django 2.1.3 on 2018-12-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appprotector', '0002_auto_20181204_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentregister',
            old_name='name',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='agentregister',
            name='Gender',
        ),
    ]
